---
RecipeFormatVersion: "2020-01-25"
ComponentName: "com.example.DeviceAgent"
ComponentVersion: "1.0.8"
ComponentType: "aws.greengrass.generic"
ComponentDescription: "Device agent component with JSON command execution via IoT Core MQTT"
ComponentPublisher: "liallan"
ComponentConfiguration:
  DefaultConfiguration:
    runWithDefault:
      posixUser: "root:root"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "com.example.DeviceAgent:pubsub:1":
          policyDescription: "Allows device agent communication via IoT Core"
          operations:
            - "aws.greengrass#PublishToIoTCore"
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - "greengrass/device-agent/*/commands"
            - "greengrass/device-agent/*/logs"
Manifests:
  - Platform:
      os: linux
      architecture: amd64
      runtime: "*"
    Lifecycle:
      run:
        Script: "{artifacts:path}/device-agent"
    Artifacts:
      - URI: "s3://liallan-greengrass-1759529680-us-west-2-728399045110/com.example.DeviceAgent/1.0.8/device-agent"
        Permission:
          Read: "ALL"
          Execute: "ALL"
      - URI: "s3://liallan-greengrass-1759529680-us-west-2-728399045110/com.example.DeviceAgent/1.0.8/examples.txt"
        Permission:
          Read: "ALL"