---
RecipeFormatVersion: "2020-01-25"
ComponentName: "com.example.FailingComponent"
ComponentVersion: "1.0.0"
ComponentType: "aws.greengrass.generic"
ComponentDescription: "A component that will fail during deployment"
ComponentPublisher: "Example Corp"
Manifests:
  - Platform:
      os: linux
      architecture: amd64
      runtime: aws_nucleus_lite
    Lifecycle:
      run:
        Script: "{artifacts:path}/failing-app"
    Artifacts:
      - URI: "s3://liallan-greengrass-1759529680-us-west-2-728399045110/com.example.FailingComponent/1.0.0/failing-app"